name = "lishenghuatools"
compatibility_date = "2026-05-08"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "tools_comments"
database_id = "5f9f017f-eaa8-4457-9458-9c0a1f1f11bf"
